disabled_rules:
    - trailing_comma

opt_in_rules:
    - closure_spacing
    - conditional_returns_on_newline
    - empty_count
    - explicit_init
    - force_unwrapping
    - overridden_super_call
    - private_outlet
    - attributes
    - number_separator
    - prohibited_super_call
    - switch_case_on_newline
    - first_where

line_length: 140
variable_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 24
    error: 32
cyclomatic_complexity:
  error: 30
