#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do
  desc 'Run tests'
  lane :test do
    spm(
      command: "generate-xcodeproj",
    )
    scan(
      code_coverage: true
    )
  end
end
