#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do
  desc 'Run tests'
  lane :test do
    scan(
      package_path: '.',
      workspace: '.',
      scheme: 'KeyboardManager',
      device: 'iPhone 8',
      result_bundle: true,
    )
  end
end
