#!usr/bin/ruby

fastlane_version "2.0"

default_platform :ios

platform :ios do
    before_all do
        ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
    end

    desc "Run tests"
    lane :test do 
        carthage(
            platform: "iOS",
            command: "bootstrap",
            use_submodules: true,
            use_binaries: true
        )
        scan(
            workspace: "KeyboardManager.xcworkspace",
            scheme: "KeyboardManager",
            sdk: "iphonesimulator",
            device: "iPhone 5s (10.2)",
            clean: true,
            code_coverage: true
        )  
        scan(
            workspace: "KeyboardManager.xcworkspace",
            scheme: "KeyboardManagerRx",
            sdk: "iphonesimulator",
            device: "iPhone 5s (10.2)",
            clean: true,
            code_coverage: true
        )  
    end
end
